settings:
  title: ''
  url: 'https://my.nextdns.io/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: hochiminh-lightnode
    name: Hồ Chí Minh LightNode
    description: 'lightnode-sgn-1.edge.nextdns.io'
    url: 'https://lightnode-sgn-1.edge.nextdns.io/resolve?name=google.com' # URL to fetch
    method: GET 
    expectStatus: 200 
    followRedirect: false 
    linkable: false 

  - id: hochiminh-greencloud
    name: Hồ Chí Minh GreenCloud
    description: 'greencloud-sgn-1.edge.nextdns.io'
    url: 'https://greencloud-sgn-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 

  - id: hanoi-lightnode
    name: Hà Nội LightNode
    description: 'lightnode-han-1.edge.nextdns.io'
    url: 'https://lightnode-han-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 

  - id: hanoi-greencloud
    name: Hà Nội GreenCloud
    description: 'greencloud-han-1.edge.nextdns.io'
    url: 'https://greencloud-han-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 

  - id: zepto-sin
    name: Singapore Zepto
    description: 'zepto-sin-1.edge.nextdns.io'
    url: 'https://zepto-sin-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 

  - id: vultr-sin
    name: Singapore Vultr
    description: 'vultr-sin-1.edge.nextdns.io'
    url: 'https://vultr-sin-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 

  - id: anexia-sin
    name: Singapore Anexia
    description: 'anexia-sin-1.edge.nextdns.io'
    url: 'https://anexia-sin-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 

  - id: anexia-hkg
    name: HongKong Anexia
    description: 'anexia-hkg-1.edge.nextdns.io'
    url: 'https://anexia-hkg-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 

  - id: zepto-hkg
    name: HongKong Zepto
    description: 'zepto-hkg-1.edge.nextdns.io'
    url: 'https://zepto-hkg-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 
